### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by artistro08** [wiz-comunicaciones/oc-webp-plugin#1]
How do I Install this plugin on my website?

**Comment by artistro08** [comment]
Figured it out. For those who want to know, add a folder called `wiz` and then clone this repository into this folder. rename the folder `webp` then in your backend, `Settings -> Updates & Plugins` and do a force update after clicking the Check for updates button

**Comment by bombozama** [comment]
you could just clone it from the root directory of your site:
```bash
git clone https://github.com/wiz-comunicaciones/webp-implementation.git plugins/wiz/webp
```

**Comment by artistro08** [comment]
Didn't want submodules in my project tho ;)
